project:
  type: website

website:
  title: "Jiexin Fan"
  description: "My Professional Portfolio"
  site-url: "https://jiexinfan.github.io"
  navbar:
    background: primary
    left:
      - text: "About Me"
        href: aboutme.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/jiexinfan
      - icon: linkedin
        href: https://www.linkedin.com/in/jiexnfan
  page-footer:
    left: "Â© 2025 Jiexin Fan. All rights reserved."
    right: "Built with [Quarto](https://quarto.org/) and hosted on GitHub Pages."

format:
  html:
    theme: minty
    css: styles.css
    toc: true
